# -*- coding: utf-8 -*-
"""Final Project 2024

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t7J-DYdY5BxW-A1707Qs61mR-zPHkEax
"""

!pip install dash
!pip install plotly

import dash
from dash import dcc, html, Input, Output
import plotly.express as px
import pandas as pd

url = "https://raw.githubusercontent.com/Carlos00Monteiro/datasets_2014/main/2014_world_gdp_with_codes.csv"
df = pd.read_csv(url)

app = dash.Dash(__name__)

app.layout = html.Div([
    html.H1("Projeto Final _ Mapa mundo GDP"),
    dcc.Graph(id='world-gdp-choropleth')
])

@app.callback(
    dash.dependencies.Output('world-gdp-choropleth', 'figure'),
    [dash.dependencies.Input('world-gdp-choropleth', 'value')]
)
def update_choropleth(value):
    fig = px.choropleth(df,
                        locations="CODE",
                        color="GDP (BILLIONS)",
                        hover_name="COUNTRY",
                        color_continuous_scale=px.colors.sequential.Plasma,
                        projection="natural earth",
                        title="World GDP Choropleth Map"
                        )
    return fig

if __name__ == '__main__':
    app.run_server(debug=True)